### ISSUE TITLE
이틀 이상 걸치거나, 종일에 대한 일정 표시하기

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/flutter-client#31]
현재 무조건 시작 날짜를 기준으로 달력에서 일정이 1칸을 차지하도록 짜여져 있다.

그런데, 이틀 이상 걸치는 일정에 대해서 서비스들 간에 처리 방식이 조금 다르다.

구글의 경우, 보면 신기하다...

- 이틀 이상 걸치더라도 정확히 `24시간 이상, 3일을 초과하여 걸치지 않는 경우' 2칸을 차지한다.
- 그 이상의 범위인 경우 종료 날짜까지 칸을 차지한다.

예를 들어

9월 11일 수요일 오후 11시 30분부터
9월 12일 목요일 오후 11시 25분까지는 1칸
9월 12일 목요일 오후 11시 30분부터는 2칸
9월 13일 금요일 오전 12시 05분부터는 3칸이다.

아무튼 달력의 그리드를 넘어서 텍스트와 막대기를 어떻게 안 끊기게 그릴까 싶고
정렬이랑 같이 고려하면서 종일이 가장 위로 가게... (종일도 종일 나름의 순서를 정하고...) 시간 순으로 하...
또 그게 다 표시할 수 없게 많은 일정이 쌓이면 어쩔건가, 표시되는 가장 아래 쪽에서 몇칸씩 차지하는 경우도 만들어보고...

일단 표시만 해보자.

**Comment by koderpark** [comment]
하루종일 고민하고 있는데 머리깨질거같네요 크아악

**Comment by koderpark** [comment]
쉬운 대안으로는 notion calendar처럼 종일 일정을 별도로 상단에 표기하는건데 이건 저희 UI랑은 안맞을거같고...

ref)
![image](https://github.com/user-attachments/assets/8d13d903-648b-4ff2-8bf5-2a3d1fee1de0)

고민중인 방안으로는 각 줄마다 index를 부여하고
먼저 range 일정을 채운 다음 빈 자리에 index를 채워넣는게 맞을거같은데 흠

**Comment by koderpark** [comment]
일단 이거할거면 캘린더랑 이벤트 파트 분리는 되어야함

**Comment by koderpark** [comment]
update : 이벤트도 별도 파일로 묶어서 관리하는 커밋을 올림
TableCalendar 라이브러리 왈 marker를 사용하면 일정 표시를 내장된 라이브러리로 할 수 있다는듯 한데, 초창기에 이걸 선택하지 않았던 특별한 이유가 있었을까요?

단순히 몰라서 안했던거면 겸사겸사 이걸로 리팩토링할까 싶은데

@call-me-bammer

**Comment by koderpark** [comment]
ref)
https://velog.io/@jun7332568/%ED%94%8C%EB%9F%AC%ED%84%B0flutter-%EB%8B%AC%EB%A0%A5-Event-%EA%B5%AC%ED%98%84%ED%95%B4%EB%B3%B4%EA%B8%B0-Tablecalendar-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC

https://pub.dev/documentation/table_calendar/latest/table_calendar/MarkerBuilder.html
+
https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/eventLoader.html

**Comment by koderpark** [comment]
<img width="335" alt="image" src="https://github.com/user-attachments/assets/d191309c-5c97-45b8-8d1d-4e082a4ec00c">

이로 말미암아 생기는 버그 몇가지 수정하고 푸시 및 이슈 닫도록 하겠습니다.

**Comment by koderpark** [comment]
간단하게 구현해둿습니다. closed.
