### ISSUE TITLE
종일 및 일반 일정 정렬하여 표시하기

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/flutter-client#32]
제곧내

기본적인 정렬 순서는 종일 일정 이후 일반 일정들의 시작 시각 순이며,
그래도 정해지지 않는다면 각 종일, 일반 일정 내에서 사전 순으로 정렬한다.

예를 들어, 이렇게 입력하면 중간점검 위아래로 저렇게 쌓인다.

![Image](https://github.com/user-attachments/assets/da9abd45-ecb4-4077-a4fc-7ca3ddb1218b)

**Comment by koderpark** [comment]
start time이 빠른 순서대로
end time이 느린 순서대로
이름 사전순 빠른 순서대로

정렬시 종일 일정 > 시간순 > 이름순 정렬이 가능해 이렇게 대응했습니다.
위젯이 빌드될 때마다 정렬 중입니다.
지금 파싱이 그냥 /api/v1/event/${i} 번 긁어오던데
이미 이벤트 갯수가 100개를 넘어서 i를 임시로 256까지 확장해뒀습니다
근데이거 시급히 수정해야하지 않나 싶고
아마 별일없으면 제가 수정할듯?

일정 가져오는 방법도 이슈에 올려놓도록 하겠습니다.
