### ISSUE TITLE
ai statistics가 생성되지 않는 이슈

### ISSUE THREAD

**Issue by inmonim** [SWM-15th-Dnight/flutter-client#6]
## 문제 사항

ai(LLM)을 활용했을 경우, 자동으로 생성되는 ai_processed_statistics, ai_processed_event 데이터가 제대로 DB에 적제되지 않는 문제.

## 원인 추적

아마도 ai를 활용한 데이터 생성 기능이 main backend의 eventProcessing/plaintText가 아니라,

ai server의 plainText로 직접 데이터를 보내고 있으리라 파악 됨.

추후 ai 서버는 외부의 요청은 막고, main backend 서버만을 통해서 통신이 가능하도록 만들 예정임.

따라서 모든 요청은 main backend로 들어와야 하며, 본 이슈의 직접적인 문제의 해결을 위해서도 위와 같은 방식을 사용하고 있다면 빠르게 수정 부탁함.

**Comment by call-me-bammer** [comment]
조치완료. #7 PR 확인하고 머-지를 부탁합니다!

**Comment by call-me-bammer** [comment]
닫기!
