### ISSUE TITLE
hands-up push notification 클라이언트 설정 및 동작 확인

### ISSUE THREAD

**Issue by call-me-bammer** [SWM-15th-Dnight/flutter-client#9]

**Comment by koderpark** [comment]
s10e에서 정상작동 확인했는데 원인을 모르겠어서 조금만 더 붙잡을거같아요
아마 오늘내로 커밋올리고 닫을듯

**Comment by koderpark** [comment]
지옥같던 동아리 OT가 끝나고 드디어 자유의 몸이 되었습니다.
일단 얘는 해결했고 원인도 파악이 끝나서 닫도록 하겠습니다.

사유 : AndroidManifest.xml 에 명시된 id가 백그라운드 쪽에 표기된것과 제대로 연동되지 않아서였던듯.
NotificationChannel의 id를 테스트 목적에서 제대로 변경시켜놓고 양쪽 다 맞춰줘서 이제 더이상
Miscellaneous 채널이 생성되지 않습니다.

ref) https://totally-developer.tistory.com/154
